export const ACTION_TYPES = {
  SET_CATEGORY_SUCCESS : 'SET_CATEGORY_SUCCESS',
  SET_CATEGORY_FAILED : 'SET_CATEGORY_FAILED',
  FETCH_CATEGORY : 'FETCH_CATEGORY',
  ADD_CART_ITEM : 'ADD_CART_ITEM',
  INC_CART_COUNT : 'INC_CART_COUNT',
  DEC_CART_COUNT : 'DEC_CART_COUNT'
}
